require 'rubygems'
require 'bundler'
begin
  Bundler.setup(:default, :development)
rescue Bundler::BundlerError => e
  $stderr.puts e.message
  $stderr.puts "Run `bundle install` to install missing gems"
  exit e.status_code
end
require 'test/unit'
require 'shoulda'
# set up lib path if testing so can test more easily
ENV['core-access_test-libpath'] = File.join(File.dirname(__FILE__), '..', 'lib')
$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), '..', 'lib'))
$LOAD_PATH.unshift(File.dirname(__FILE__))

@@representative_of_cluster1_sequence = "atgaatagagaggctttattaattgttagtaacgggcagcaatgtcataaaaaccacttgtctcctgaaaaagtcgtgacaattgggaatacaatcgaacacgaaatcacttatcctgaactggctgagtcgattgaagttaaatacgatgaaggctcttggaatgctggaacaacagcgctccaagcgaatcaagctgtaaatgtagagaacttagcattctatctatgccaagatttacatacacaagtttatgatgttgtaacgaatatttctgtgacatttggcgttggaatagaaaatgatgtcacattagatgatacaaaatcagattttatacttttacgtgatgcaaaggaaaaactgtttaagttacaagtcttaaatggcgaagtttatcataacttttctctagtaacggaagactgcgttctagaaccgggtgatcagctctatacggacggtgtgacgattacaatcggaaaagaagatattagtgtgctagctgtgaaaaatcgcgtgacgagcaaattagcgcctttatttgctgcggacaattcgttcggggaagattatccggattaccaccgttcaccgcggattatttaccgtgcgccagaagaaaaaatcagcatggcgaaaccgtcaagtaaaccctcaaaaccaacagatggcttaattaaaattattttaccaccccttatcatggtggcaattacggtcatgatttccattttccaaccacgtggactttatattattatgacaatcgcaatgtcagcagtgacaatcacaatggcgattcttaactacataaaatcacgtaaaaaatacaaaatcgattccaaacaacgcgtggaaagctacgatttgtatttaaaacgaaaaacgaaagaattgcacgaaacaagcgaaaaacagcgtcacgctttaacctatcactatccagacgtaactgaactagaaaaaatggcgttacgtgtggattcgcggatttacgaaaaaacaatgttccatcatgatttcttgactttccgagttggtcgaggcgacgaagcaagtagcttttccgtggaattccaacaggaagagttcagccaagaaaaagacgaacttgtagaagaagctgtgaaaattaaagggcaatatttatcaatcaatgaagtgccagttgcgacagatttaatgcacggaccagtggggtatatcgggccacgccgtttagtattagaacaactgcaaatgttagtaatgcaaacatcccttttccatagttattatgatttgcaatttattacgattttcccagaagaagagaaggcggattgggactggatgcgctggctaccgcatgcgaatatgcgtgatgtgaatgtgcgtggttttgtttaccatgaacgttcgcgcgaccaagtgttgaactcgctttatcaaattttaaaagagcgtaaacaagcgcttactgaacaagcgagcaaacaggaaaaattatactttacgccacattatgtggttttaattaccgacgaaaaattagtactcgatcacacggttatggaattcttcaatgaagatccaagcgaactaggtgtttctttagtgttcgtacaggacgtaatggagagcttgccagaacacgtgaaaacggtcgtggatattcgtgatgcgaagagcgggaacattattttggaacaaggcgaccttgtaaaccgagcgttcgtgccggatcatttgccagcagattttgacaaagaagtaatcagccgggctcttgcgccgctaaaccatcttcaaaacttgaaaaactcgatcccagaatccgttacttttcttgaaatgtacggtgtagagcgcgtcgaagagttaaacattgctggacgctgggcgaaaaatgaaacgtataagagccttgctgtaccacttggcttgcgcggaaaagacgatatcgttcaactgaatttacatgaaaaagcgcacgggccgcatggtttggtagccggaacaactggttctggtaaatcagaaatcattcagtcttacattatctcacttggcgtcaatttccacccatatgaagtcgcgttcttgctgattgactataagggcggcggtatggcgaacttatttaaaaatatgccacatttactgggaacaattacaaacttggacggcgcgcaatccatgcgtgcactagcttccatcaaagccgaattgcagaaaaggcaacggttatttggcgagcacgatgttaaccacatcaaccaataccaaaaactatacaaacaaggaaaagcgaccgaaccaatgccgcatttattccttatttcagatgagttcgccgagttgaaatcagaacaaccagaattcatgaaagaacttgtttcgacagcacgtatcgggcgttcactcggaatccatttaatcctagcaacccaaaaaccaagtggcgtcgtggatgaccaaatctggtccaactccaaattcaaactagccctcaaagtacaaaacgccagcgattcaaacgaaattttgaaaacaccagacgcagcagaaatcacactaccaggccgttcgtacttgcaagttggtaataacgaaatttacgaactgttccaaagtgcttggagtggtgcggattacgtgccagataaggaaagcacggattatattgatacgacgatttatgcgattaatgatttaggtcagtatgatattttgacagaggatttgagcggattagataagaaggatgatttgactaagttgccgagtgaacttgatgcggtgattgatcatattcatgcgtatacggaggcttctgggattaaggcgttgccgagaccttggttgccgccgctacctgaacgaattttcgcccaagacttacatccagtcaattttgaagaagcatggaaagaaccgaaaaaaccacttcaagcaacaattggtttactggatcaacccgaattacaagcacaagtcccattaacactcgatttaacaaaagatggacacgtggctgtattctcaagtccagggtttgggaaatccaccttcttgcaaagtttagtgatggatttagctcgtcaacataatccagagcaactgcatgtttatttgttggattttgggacgaatgggttgctacctctagtagatctgccacatattgctgatacaatgatggtggatgaagttgaaaaaatacagaaatttttacgaatctgcctaaatgaaataaaaacaaggaagaagcttcttagccaatatcgtgttgcaaatatagagcagtatgaaagagcaagtggaaaagaactacctaatattattgttgttctagataattacgacgctgtaaaagatgcaggcttaggggatgattttgaaaaaatcattactcaaattactcgtgaaggtgcatccattggaatgtttatgattattagcgcatcaaggcatatgagtttgagaacacaaatggctactaatattaaacaaatgattgctttatatctaattgataaaaatgatatatcatcaactgttggtcgaacggatacaccacttgaagagtatccaggaagagcgcttgtaaaattagaaacagttacaacatttcaaacgacgttaccatcgcacggagaagaaacaattcaacagattgaaggtattcgaaatgaagcaaaattaatgagagaaggttggcaaggagaacttccagagagcgtaccaatgattccagaaaaaattaaactagctgatttttgtgaatggatggaaactaaagaggtcgttgcaaatggaaatatacctatcggagttgattttgaatacgtaaaaccagtaggcattgattacaagcaaaccggagtactaattattgcagatgtaattggacgaaacttagtaagcataaataaaaatgtagctaattctcttgtgcaaaatccaaatatttctctcttaattagcgacacagcgaattttgatttagtggaaatgtctactaaagccaatttatacagtaacaacacagaggatttgaagcagaatatgaaaaaagtactctctatttatcaatccagaactgaaaaagcagatgaacttcgaaaagcaggagataatttaggcgtaactgccatgattcaaggattaaaagatatagttgctttcgtaggagattacgatatcttactaaaaactcttgatgaagaagaccaaaaagttctaatagatatgattaacaatggaaaaacatatggttgctatttaattttaagtggttcgattcaagcatttaaaggatatggtgatttgaataaagctgttcaagctcaaagaaactatatattctttgatcgactatcgaattcaagcccattctccttctcgtttaatatttatagagaacaagaattattacctgaggaaggttatgtaatagcaggacaagagtggcaaaaaataaaaattgcaaaatatgaagaagaggtgtaa"
@@representative_of_cluster2_sequence = "ttgctgtataaaaataatagtgattctggaaaagtatacaattttttatccgaaaaattgaaaaagttaacaaaaggggaaggtgtttgtgaaaaaggcatctttttgtatagtgatgttgtttttaaaagacctattatcaagtctttatag"

def silence &block
  default_stdout = $stdout
  $stdout = StringIO.new
  yield
  $stdout.string
ensure
  $stdout = default_stdout
end

class Test::Unit::TestCase
end
