# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "core-access"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Anthony Underwood"]
  s.date = "2012-03-13"
  s.description = "Using simple or rich sequences as input, this gem will build a database that can be queried to find the distribution of genes in specific subsets of the input sequences"
  s.email = "email2ants@gmail.com"
  s.executables = ["core-access"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/core-access",
    "lib/bioutils/blast.rb",
    "lib/bioutils/glimmer.rb",
    "lib/bioutils/ncbi_blast.rb",
    "lib/bioutils/reciprocal_hit.rb",
    "lib/bioutils/rich_sequence_utils.rb",
    "lib/core-access.rb",
    "lib/core-access/cluster_classes.rb",
    "lib/core-access/cluster_database.rb",
    "lib/core-access/cluster_models.rb",
    "lib/core-access/clustering_methods.rb",
    "lib/genome/genome_reciprocal_hit_annotator.rb",
    "lib/utils/file_utils.rb",
    "lib/utils/hash_reverse_merge.rb",
    "lib/utils/method_argument_parser.rb",
    "test/fasta_sequence_file_list.txt",
    "test/genbank_sequence_file_list.txt",
    "test/helper.rb",
    "test/test_core-access.rb",
    "test/test_data/cdhit_clusters-85",
    "test/test_data/cdhit_clusters-85.bak.clstr",
    "test/test_data/cdhit_clusters-85.clstr",
    "test/test_data/cdhit_clusters-90",
    "test/test_data/cdhit_clusters-90.bak.clstr",
    "test/test_data/cdhit_clusters-90.clstr",
    "test/test_data/cdhit_clusters-95",
    "test/test_data/cdhit_clusters-95.bak.clstr",
    "test/test_data/cdhit_clusters-95.clstr",
    "test/test_data/cdhit_clusters-98",
    "test/test_data/cdhit_clusters-98.bak.clstr",
    "test/test_data/cdhit_clusters-98.clstr",
    "test/test_data/cdhit_clusters-99",
    "test/test_data/cdhit_clusters-99.bak.clstr",
    "test/test_data/cdhit_clusters-99.clstr",
    "test/test_data/cds_proteins.fas",
    "test/test_data/ref.gbk",
    "test/test_data/ref_seq1.gbk",
    "test/test_data/ref_seq2.gbk",
    "test/test_data/seq1.fas",
    "test/test_data/seq1.fas.sslist",
    "test/test_data/seq1.gbk",
    "test/test_data/seq2.fas",
    "test/test_data/seq2.fas.sslist",
    "test/test_data/seq2.gbk",
    "test/test_data/test_with_representatives.sqlite",
    "test/test_data/test_with_superclusters.sqlite",
    "test/test_data/test_without_representatives.sqlite"
  ]
  s.homepage = "http://github.com/hpa-bioinformatics/core-access"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.17"
  s.summary = "Prokaryotic core and accessory gene database builder"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bio>, ["~> 1.4.2"])
      s.add_runtime_dependency(%q<choice>, ["~> 0.1.5"])
      s.add_runtime_dependency(%q<activerecord>, ["~> 3.2.2"])
      s.add_runtime_dependency(%q<sqlite3>, ["~> 1.3.5"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<bio>, ["~> 1.4.2"])
      s.add_dependency(%q<choice>, ["~> 0.1.5"])
      s.add_dependency(%q<activerecord>, ["~> 3.2.2"])
      s.add_dependency(%q<sqlite3>, ["~> 1.3.5"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<bio>, ["~> 1.4.2"])
    s.add_dependency(%q<choice>, ["~> 0.1.5"])
    s.add_dependency(%q<activerecord>, ["~> 3.2.2"])
    s.add_dependency(%q<sqlite3>, ["~> 1.3.5"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

